CREATE TABLE personalworkbench.`user` (
  ID INT NOT NULL AUTO_INCREMENT,
  userID VARCHAR(45) NOT NULL,
  userPass VARCHAR(45) NOT NULL,
  name VARCHAR(45) NOT NULL,
  sex VARCHAR(45) NOT NULL,
  personalID VARCHAR(45) NOT NULL,
  number VARCHAR(45) NOT NULL,
  address VARCHAR(45) NULL,
  date VARCHAR(45) NOT NULL,
  authority VARCHAR(45) NOT NULL,
  personalPic VARCHAR(45) NULL,

  others VARCHAR(45) NULL,
  others1 VARCHAR(45) NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX userID_UNIQUE (userID ASC),
  UNIQUE INDEX ID_UNIQUE (ID ASC),
  UNIQUE INDEX personalID_UNIQUE (personalID ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;